Update bayes.py
hoice: 4

Search 4 Results 1 = Not Found
Search 4 Results 2 = Found in Area 2.

Search 4 Effectiveness (E):
E1 = 0.757, E2 = 0.619, E3 = 0.000
Traceback (most recent call last):
  File "bayes.py", line 243, in <module>
    main()
  File "bayes.py", line 236, in main
    cv.circle(app.img, (sailor_x, sailor_y), 3, (255, 0, 0), -1)
TypeError: only integer scalar arrays can be converted to a scalar index
luke@luke-Latitude-E5420:~/Scripts/Python/KBs/REAL_WORL_PYTHON$